forumflask/flaskforum/main/routes.py
from flask import render_template, request, Blueprint
from flaskforum.models import Post, Vote, Reply, User
from flask_login import current_user, login_required
from flaskforum.replies.forms import ReplyForm

main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
	votes = Vote.query.all()
	form = ReplyForm()
	replies = Reply.query.all()
	return render_template('home.html', title = 'Home', 
		posts = posts, votes = votes, form = form, replies = replies, page = page)



forumflask/flaskforum/posts/routes.py
from flask import render_template, redirect, flash, request, abort, Blueprint, url_for
from flask_login import current_user, login_required
from flaskforum import db
from flaskforum.models import Post
from flaskforum.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form= PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content = form.content.data, author = current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created', 'success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title = 'New Post',
		form = form, legend = 'New Post', action = 'Create')

@posts.route("/post/<int:post_id>/update", methods = ['GET','POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash('Your post has been updated', 'success')
		return redirect(url_for('users.my_posts'))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title = 'Update Post',
		form = form, legend = 'New Post', action = 'Update')

@posts.route("/post/<int:post_id>/delete", methods = ['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been deleted', 'info')
	return redirect(url_for('users.my_posts'))

forumflask/flaskforum/users/routes.py
from flask import render_template, current_app, url_for, flash, redirect, request, Blueprint
from flask_login import login_required, login_user, current_user, logout_user
from flaskforum.users.forms import LoginForm, RegisterForm, UpdateAccountForm
from flaskforum.replies.forms import ReplyForm
from flaskforum import db, bcrypt
from flaskforum.models import User, Post, Vote, Reply
import os
import secrets
from PIL import Image

users = Blueprint('users', __name__)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated!'+current_user.image_file, 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profiles/' + current_user.image_file)
	return render_template('account.html', title = 'Account',
		image_file=image_file, form=form)

@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegisterForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username = form.username.data, email=form.email.data, password = hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your account has been created','success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title = 'Register', form =form)

@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember = form.remember.data)
			flash('You have been logged in', 'success')
			return redirect(url_for('main.home'))
		else:
			flash('Unsucessful login','danger')
	return render_template('login.html', title = 'Login', form =form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route("/my_posts")
@login_required
def my_posts():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.filter_by(user_id = current_user.id)\
		.order_by(Post.date_posted.desc())\
		.paginate(page=page, per_page=5)
	type = 'post'
	return render_template('my_posts.html', title = 'My Posts', posts = posts
		, type = type)

@users.route("/my_likes")
@login_required
def my_likes():
	page = request.args.get('page', 1, type=int)
	votes = Vote.query.filter_by(user_id = current_user.id, action = 1)
	p = []
	for vote in votes:
		p.append(vote.post_id)
	posts = Post.query.filter(Post.id.in_(p))\
		.order_by(Post.date_posted.desc())\
		.paginate(page=page, per_page=5)
	votes = Vote.query.all()
	form = ReplyForm()
	replies = Reply.query.all()
	return render_template('my_posts.html', title = 'My Likes', posts = posts, 
		type = 'like',votes = votes, form = form, replies = replies, page = page)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/profiles', picture_fn)

    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

forumflask/flaskforum/votes/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required, login_user, current_user, logout_user
from flaskforum import db
from flaskforum.models import User, Post, Vote

votes = Blueprint('votes', __name__)

@votes.route("/<int:user_id>/<int:post_id>/<int:page>/upvote", methods = ['POST'])
@login_required
def upvote(user_id, post_id,page):
	vote = Vote.query.filter_by(user_id = user_id, post_id = post_id, action = 1).first()
	down = Vote.query.filter_by(user_id = user_id, post_id = post_id, action = -1).first()
	if vote:
		db.session.delete(vote)
		db.session.commit()
	if not vote:
		post = Post.query.get_or_404(post_id)
		vote = Vote(action = 1, user = current_user, post = post)
		if down:
			db.session.delete(down)
		db.session.add(vote)
		db.session.commit()
		flash('You have successfully voted!', 'success')
	return redirect(url_for('main.home', page=page))

@votes.route("/<int:user_id>/<int:post_id>/<int:page>/downvote", methods = ['POST'])
@login_required
def downvote(user_id, post_id, page):
	vote = Vote.query.filter_by(user_id = user_id, post_id = post_id, action = -1).first()
	up = Vote.query.filter_by(user_id = user_id, post_id = post_id, action = 1).first()
	if vote:
		db.session.delete(vote)
		db.session.commit()
	if not vote:
		post = Post.query.get_or_404(post_id)
		vote = Vote(action = -1, user = current_user, post = post)
		if up:
			db.session.delete(up)
		db.session.add(vote)
		db.session.commit()
		flash('You have successfully voted!', 'success')
	return redirect(url_for('main.home', page=page))

forumflask/flaskforum/templates/account.html
{%extends "layout.html"%}
{%block content%}

	<form class='p-5'  method="POST" action="" enctype="multipart/form-data">
	  {{ form.hidden_tag() }}
	  <div class='row'>
	  	<img class="rounded-circle account-img" src="{{ image_file }}">
		 <h1 class="border-bottom mb-4 p-5">{{ current_user.username }}</h1>
	  </div>
	  <div class="form-group">
	    {{form.username.label(class="form-control-label")}}
	    {%if form.username.errors%}
	      {{form.username(class = "form-control form-control-lg is-invalid")}}
	      <div class = "invalid-feedback">
	        {%for error in form.username.errors%}
	          <span>{{error}}</span>
	        {%endfor%}
	      </div>
	    {%else%}
	      {{form.username(class = "form-control form-control-lg")}}
	    {%endif%}
	  </div>
	  <div class="form-group">
	    {{form.email.label(class="form-control-label")}}
	    {%if form.email.errors%}
	      {{form.email(class = "form-control form-control-lg is-invalid")}}
	      <div class = "invalid-feedback">
	        {%for error in form.email.errors%}
	          <span>{{error}}</span>
	        {%endfor%}
	      </div>
	    {%else%}
	      {{form.email(class = "form-control form-control-lg")}}
	    {%endif%}
	  </div>
	  <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
            {% endif %}
        </div>
	  <div class="border-top pt-3">
	    {{ form.submit(class="btn btn-outline-info") }}
	  </div>
	</form>
{% endblock content %}

forumflask/flaskforum/templates/create_post.html
{%extends "layout.html"%}
{%block content%}
<form class='p-5' method="POST" action="">
  {{ form.hidden_tag() }}
	<h3>{{action}} Post</h3>
  <div class="form-group">
    {{form.title.label(for="form-control-label")}}
    {%if form.title.errors%}
      {{form.title(class = "form-control form-control-lg is-invalid")}}
      <div class = "invalid-feedback">
        {%for error in form.title.errors%}
          <span>{{error}}</span>
        {%endfor%}
      </div>
    {%else%}
      {{form.title(class = "form-control form-control-lg")}}
    {%endif%}
  </div>
  <div class="form-group">
	    {{ form.content.label(class="form-control-label") }}
	    {% if form.content.errors %}
	        {{ form.content(class="form-control form-control-lg is-invalid") }}
	        <div class="invalid-feedback">
	            {% for error in form.content.errors %}
	                <span>{{ error }}</span>
	            {% endfor %}
	        </div>
	    {% else %}
	        {{ form.content(class="form-control form-control-lg") }}
	    {% endif %}
	</div>
  <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
</form>
{%endblock%}

forumflask/flaskforum/templates/home.html
{%extends "layout.html"%}
{%block content%}
  {%for post in posts.items%}
    <article class="border rounded m-5 p-2">
      <h3>{{post.title}}</h3>
      <div>
        <img src="{{ url_for('static', filename='profiles/' + post.author.image_file) }}" class="float-left rounded-circle" style="width: 40px; height: 40px;">
        <h6 class="text-muted p-2" style="height: 40px;">{{post.author.username}}</h6>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      <p style = "white-space: pre-line;">
        {{post.content}}
      </p>
      </div>
      {% if current_user.is_authenticated%}
      <div>
        <div class='row ml-2'>
          {%set count = namespace(a=0)%}
          {%set v = namespace(a=0)%}
            {%for vote in votes%}
            {%if vote.post_id == post.id and vote.user_id == current_user.id%}
              {%if vote.action==1%}
              {%set v.a = 1%}
              {%endif%}
              {%if vote.action==-1%}
              {%set v.a = -1%}
              {%endif%}
            {%endif%}
          </form>
              {%if vote.post_id == post.id%}
                {%if vote.action == 1%}
              {%set count.a = count.a + 1%}
                {%else%}
                {%set count.a = count.a - 1%}
                {%endif%}
              {%endif%}
            {%endfor%}
            {%if v.a == 1%}
            <form action="{{ url_for('votes.upvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-light btn-outline-secondary" type="submit" value="Upvote">
              </form>
                <form action="{{ url_for('votes.downvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-dark btn-primary" type="submit" value="Downvote">
              </form>
              {%endif%}
            {%if v.a==-1%}
                <form action="{{ url_for('votes.upvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-light btn-primary" type="submit" value="Upvote">
              </form>
                <form action="{{ url_for('votes.downvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-dark btn-outline-secondary" type="submit" value="Downvote"></form>
            {%endif%}
            {%if v.a==0%}
                <form action="{{ url_for('votes.upvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-light btn-primary" type="submit" value="Upvote">
              </form>
                <form action="{{ url_for('votes.downvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-dark btn-primary" type="submit" value="Downvote">
              </form>
            {%endif%}
          <h6 class='m-2'>The number of upvote is 
          {{count.a}}
          </h6>
        </div>
        <div class='mt-2'>
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample+{{post.id}}" aria-expanded="false" aria-controls="collapseExample+{{post.id}}">
            See All Replies
          </button>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#replyModal{{post.id}}">Reply</button>
        </div>
          
          <div class="collapse" id="collapseExample+{{post.id}}">
            {%for reply in replies%}
              {%if reply.post_id == post.id%}
              <div>
                <div class="dropdown-divider"></div>
                <div >
                  <img src="{{ url_for('static', filename='profiles/' + reply.user.image_file) }}" class="rounded-circle float-left" style="width: 20px; height: 20px;">
                  <h6 class="text-muted" style="height: 20px;">{{reply.user.username}}</h6>
                  <small class="text-muted text-right">{{ reply.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <p class = "pt-0" style = "white-space: pre-line;">
                  {{reply.content}}
                </p>
              </div>
              {%endif%}
            {%endfor%}
          </div>

          <div class="modal fade" id="replyModal{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel{{post.id}}" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Reply</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form class='p-5' method="POST" action="{{ url_for('replies.reply_post',user_id = current_user.id, post_id=post.id, page = page) }}" >
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                              {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>

          </div>
          {%endif%}
    </article>
  {%endfor%}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  {% endblock content %}

forumflask/flaskforum/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% if title %}
        <title>Flask Forum - {{ title }}</title>
    {% else %}
        <title>Flask Forum</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{{ url_for('main.home') }}">FlaskForum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto nav-pills">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
  </div>
  {% if current_user.is_authenticated%}
  <ul class="nav justify-content-end nav-pills">
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
  </li>
  </ul>
  {%else%}
  <ul class="nav justify-content-end nav-pills">
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
  </li>
</ul>
{%endif%}
</nav>
<main>
  <div class="col-md-11 pt-4">
    <div class="row">
        <div class="col-md-10">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        {% if current_user.is_authenticated%}
        <div class="col-md-2 pt-5">
         <!-- <div class="content-section">
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                  <a class="nav-link" href="{{ url_for('users.my_posts') }}">My Posts</a>
                </li>
                <li class="list-group-item list-group-item-light">
                  <a class="nav-link" href="{{ url_for('users.my_likes') }}">My Likes</a></li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
          </div>-->
          <nav class="nav flex-column container">
            <div class="dropdown-divider"></div>
            <a class="nav-link" href="{{ url_for('users.my_posts') }}">My Posts</a>
            <div class="dropdown-divider"></div>
            <a class="nav-link" href="{{ url_for('users.my_likes') }}">My Likes</a>
            <div class="dropdown-divider"></div>
          </nav>
        </div>
        {%endif%}
      </div>
	
</main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

forumflask/flaskforum/templates/my_posts.html
{%extends "layout.html"%}
{%block content%}
	{%for post in posts.items%}
		<article class="border rounded m-5 p-2">
			<h3>{{post.title}}</h3>
			<div>
				<img src="{{ url_for('static', filename='profiles/' + post.author.image_file) }}" class="float-left rounded-circle" style="width: 40px; height: 40px;">
				<h6 class="text-muted p-2" style="height: 40px;">{{post.author.username}}</h6>
				<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
			</div>
			<p style = "white-space: pre-line;">
				{{post.content}}
			</p>
					      {%if type == 'post'%}
			<div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
		<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title">Delete Post?</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-footer">

		        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
		      </div>
		      {%else%}
      <div>
        <div class='row ml-2'>
          {%set count = namespace(a=0)%}
          {%set v = namespace(a=0)%}
            {%for vote in votes%}
            {%if vote.post_id == post.id and vote.user_id == current_user.id%}
              {%if vote.action==1%}
              {%set v.a = 1%}
              {%endif%}
              {%if vote.action==-1%}
              {%set v.a = -1%}
              {%endif%}
            {%endif%}
          </form>
              {%if vote.post_id == post.id%}
                {%if vote.action == 1%}
              {%set count.a = count.a + 1%}
                {%else%}
                {%set count.a = count.a - 1%}
                {%endif%}
              {%endif%}
            {%endfor%}
            {%if v.a == 1%}
            <form action="{{ url_for('votes.upvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-light btn-outline-secondary" type="submit" value="Upvote">
              </form>
                <form action="{{ url_for('votes.downvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-dark btn-primary" type="submit" value="Downvote">
              </form>
              {%endif%}
            {%if v.a==-1%}
                <form action="{{ url_for('votes.upvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-light btn-primary" type="submit" value="Upvote">
              </form>
                <form action="{{ url_for('votes.downvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-dark btn-outline-secondary" type="submit" value="Downvote"></form>
            {%endif%}
            {%if v.a==0%}
                <form action="{{ url_for('votes.upvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-light btn-primary" type="submit" value="Upvote">
              </form>
                <form action="{{ url_for('votes.downvote',user_id = current_user.id, post_id=post.id, page=page) }}" method="POST">
                <input class="btn btn-dark btn-primary" type="submit" value="Downvote">
              </form>
            {%endif%}
          <h6 class='m-2'>The number of upvote is 
          {{count.a}}
          </h6>
        </div>
        <div class='mt-2'>
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample+{{post.id}}" aria-expanded="false" aria-controls="collapseExample+{{post.id}}">
            See All Replies
          </button>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#replyModal{{post.id}}">Reply</button>
        </div>
          
          <div class="collapse" id="collapseExample+{{post.id}}">
            {%for reply in replies%}
              {%if reply.post_id == post.id%}
              <div>
                <div class="dropdown-divider"></div>
                <div >
                  <img src="{{ url_for('static', filename='profiles/' + reply.user.image_file) }}" class="rounded-circle float-left" style="width: 20px; height: 20px;">
                  <h6 class="text-muted" style="height: 20px;">{{reply.user.username}}</h6>
                  <small class="text-muted text-right">{{ reply.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <p class = "pt-0" style = "white-space: pre-line;">
                  {{reply.content}}
                </p>
              </div>
              {%endif%}
            {%endfor%}
          </div>

          <div class="modal fade" id="replyModal{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel{{post.id}}" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Reply</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form class='p-5' method="POST" action="{{ url_for('replies.reply_post',user_id = current_user.id, post_id=post.id, page = page) }}" >
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                              {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
		      {%endif%}
</article>

	{%endfor%}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.my_posts', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.my_posts', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
	{% endblock content %}